// <auto-generated />
using System;
using System.Collections.Generic;
using CarRental.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarRental.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529124228_AddIsShuttleOnlyToCar")]
    partial class AddIsShuttleOnlyToCar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "aal_level", new[] { "aal1", "aal2", "aal3" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "code_challenge_method", new[] { "s256", "plain" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "factor_status", new[] { "unverified", "verified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "factor_type", new[] { "totp", "webauthn", "phone" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_authorization_status", new[] { "pending", "approved", "denied", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_client_type", new[] { "public", "confidential" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_registration_type", new[] { "dynamic", "manual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_response_type", new[] { "code" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "one_time_token_type", new[] { "confirmation_token", "reauthentication_token", "recovery_token", "email_change_token_new", "email_change_token_current", "phone_change_token" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "realtime", "action", new[] { "INSERT", "UPDATE", "DELETE", "TRUNCATE", "ERROR" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "realtime", "equality_op", new[] { "eq", "neq", "lt", "lte", "gt", "gte", "in" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "storage", "buckettype", new[] { "STANDARD", "ANALYTICS", "VECTOR" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pg_stat_statements");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "uuid-ossp");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vault", "supabase_vault");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarRental.Api.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BookingType")
                        .HasColumnType("text");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("DropoffLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("dropoff_location_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int?>("FinalOdometer")
                        .HasColumnType("integer")
                        .HasColumnName("final_odometer");

                    b.Property<int?>("InitialOdometer")
                        .HasColumnType("integer")
                        .HasColumnName("initial_odometer");

                    b.Property<string>("LencoReference")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("payment_status")
                        .HasDefaultValueSql("'Pending'::text");

                    b.Property<Guid>("PickupLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_location_id");

                    b.Property<string>("RentalAgreementUrl")
                        .HasColumnType("text")
                        .HasColumnName("rental_agreement_url");

                    b.Property<decimal?>("SecurityDepositAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("security_deposit_amount");

                    b.Property<string>("SecurityDepositStatus")
                        .HasColumnType("text")
                        .HasColumnName("security_deposit_status");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'::text");

                    b.Property<decimal?>("TotalPriceUsd")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_price_usd");

                    b.Property<decimal>("TotalPriceZmw")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_price_zmw");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("bookings_pkey");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DropoffLocationId");

                    b.HasIndex("PickupLocationId");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("CarRental.Api.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CurrentOdometer")
                        .HasColumnType("integer")
                        .HasColumnName("current_odometer");

                    b.Property<decimal?>("DailyRateUsd")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("daily_rate_usd");

                    b.Property<decimal>("DailyRateZmw")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("daily_rate_zmw");

                    b.PrimitiveCollection<List<string>>("Features")
                        .HasColumnType("text[]")
                        .HasColumnName("features");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fuel_type");

                    b.PrimitiveCollection<List<string>>("ImageUrls")
                        .HasColumnType("text[]")
                        .HasColumnName("image_urls");

                    b.Property<DateOnly?>("InsuranceExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("insurance_expiry_date");

                    b.Property<bool>("IsShuttleOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_plate");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<DateOnly?>("RoadTaxExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("road_tax_expiry_date");

                    b.Property<int>("Seats")
                        .HasColumnType("integer")
                        .HasColumnName("seats");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Available'::text");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transmission");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vin");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("cars_pkey");

                    b.HasIndex("LocationId");

                    b.HasIndex(new[] { "LicensePlate" }, "cars_license_plate_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Vin" }, "cars_vin_key")
                        .IsUnique();

                    b.ToTable("cars", (string)null);
                });

            modelBuilder.Entity("CarRental.Api.Models.Damage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.PrimitiveCollection<List<string>>("ImageUrls")
                        .HasColumnType("text[]")
                        .HasColumnName("image_urls");

                    b.Property<decimal?>("RepairCostEstimate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("repair_cost_estimate");

                    b.Property<string>("RepairStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("repair_status")
                        .HasDefaultValueSql("'Pending'::text");

                    b.Property<Guid?>("ReportedByProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by_profile_id");

                    b.Property<string>("Severity")
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.HasKey("Id")
                        .HasName("damages_pkey");

                    b.HasIndex("BookingId");

                    b.HasIndex("CarId");

                    b.HasIndex("ReportedByProfileId");

                    b.ToTable("damages", (string)null);
                });

            modelBuilder.Entity("CarRental.Api.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("locations_pkey");

                    b.HasIndex(new[] { "Name" }, "locations_name_key")
                        .IsUnique();

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("CarRental.Api.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("notifications_pkey");

                    b.HasIndex("ProfileId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("CarRental.Api.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("AmountUsd")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount_usd");

                    b.Property<decimal>("AmountZmw")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount_zmw");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text")
                        .HasColumnName("transaction_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("payments_pkey");

                    b.HasIndex("BookingId");

                    b.HasIndex("ProfileId");

                    b.HasIndex(new[] { "TransactionId" }, "payments_transaction_id_key")
                        .IsUnique();

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("CarRental.Api.Models.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateOnly>("DriverLicenseExpiry")
                        .HasColumnType("date")
                        .HasColumnName("driver_license_expiry");

                    b.Property<string>("DriverLicenseNumber")
                        .HasColumnType("text")
                        .HasColumnName("driver_license_number");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("profiles_pkey");

                    b.HasIndex(new[] { "DriverLicenseNumber" }, "profiles_driver_license_number_key")
                        .IsUnique();

                    b.HasIndex(new[] { "PhoneNumber" }, "profiles_phone_number_key")
                        .IsUnique();

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("CarRental.Api.Models.Booking", b =>
                {
                    b.HasOne("CarRental.Api.Models.Car", "Car")
                        .WithMany("Bookings")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("bookings_car_id_fkey");

                    b.HasOne("CarRental.Api.Models.Profile", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("bookings_customer_id_fkey");

                    b.HasOne("CarRental.Api.Models.Location", "DropoffLocation")
                        .WithMany("BookingDropoffLocations")
                        .HasForeignKey("DropoffLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("bookings_dropoff_location_id_fkey");

                    b.HasOne("CarRental.Api.Models.Location", "PickupLocation")
                        .WithMany("BookingPickupLocations")
                        .HasForeignKey("PickupLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("bookings_pickup_location_id_fkey");

                    b.Navigation("Car");

                    b.Navigation("Customer");

                    b.Navigation("DropoffLocation");

                    b.Navigation("PickupLocation");
                });

            modelBuilder.Entity("CarRental.Api.Models.Car", b =>
                {
                    b.HasOne("CarRental.Api.Models.Location", "Location")
                        .WithMany("Cars")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("cars_location_id_fkey");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CarRental.Api.Models.Damage", b =>
                {
                    b.HasOne("CarRental.Api.Models.Booking", "Booking")
                        .WithMany("Damages")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("damages_booking_id_fkey");

                    b.HasOne("CarRental.Api.Models.Car", "Car")
                        .WithMany("Damages")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("damages_car_id_fkey");

                    b.HasOne("CarRental.Api.Models.Profile", "ReportedByProfile")
                        .WithMany("Damages")
                        .HasForeignKey("ReportedByProfileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("damages_reported_by_profile_id_fkey");

                    b.Navigation("Booking");

                    b.Navigation("Car");

                    b.Navigation("ReportedByProfile");
                });

            modelBuilder.Entity("CarRental.Api.Models.Notification", b =>
                {
                    b.HasOne("CarRental.Api.Models.Profile", "Profile")
                        .WithMany("Notifications")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("notifications_profile_id_fkey");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CarRental.Api.Models.Payment", b =>
                {
                    b.HasOne("CarRental.Api.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("payments_booking_id_fkey");

                    b.HasOne("CarRental.Api.Models.Profile", "Profile")
                        .WithMany("Payments")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("payments_profile_id_fkey");

                    b.Navigation("Booking");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CarRental.Api.Models.Booking", b =>
                {
                    b.Navigation("Damages");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CarRental.Api.Models.Car", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Damages");
                });

            modelBuilder.Entity("CarRental.Api.Models.Location", b =>
                {
                    b.Navigation("BookingDropoffLocations");

                    b.Navigation("BookingPickupLocations");

                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarRental.Api.Models.Profile", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Damages");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
